{{- if not .Values.lockbox.existingSecret -}}
{{- include "lockbox.requireEndpoint" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lockbox.configSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lockbox.labels" . | nindent 4 }}
type: Opaque
stringData:
  endpoint: {{ .Values.lockbox.endpoint | quote }}
  {{- if .Values.lockbox.apiKey }}
  api-key: {{ .Values.lockbox.apiKey | quote }}
  {{- end }}
{{- end -}}
