{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lockbox.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lockbox.labels" . | nindent 4 }}
{{- end -}}
