{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lockbox.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lockbox.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "lockbox.selectorLabels" . | nindent 4 }}
{{- end -}}
