# SPDX-FileCopyrightText: Hadi Cherkaoui <contact@hide.cherkaoui.ch>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: lockbox-k8s-controller
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
